# Generated by Django 3.2.20 on 2023-09-10 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zingypay', '0002_payment_tokenconversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='stellaraccount',
            name='home_domain',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='stellaraccount',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stellaraccount',
            name='balance',
            field=models.DecimalField(decimal_places=7, default='', max_digits=20),
        ),
        migrations.AlterField(
            model_name='stellaraccount',
            name='mnemonic',
            field=models.CharField(default='', max_length=100),
        ),
    ]
