# Generated by Django 3.2.20 on 2023-09-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zingypay', '0003_auto_20230910_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stellaraccount',
            name='balance',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
    ]
