# Generated by Django 3.2.20 on 2023-09-11 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zingypay', '0004_alter_stellaraccount_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stellaraccount',
            name='balance',
            field=models.DecimalField(decimal_places=7, default='', max_digits=20),
        ),
    ]
